Rscript R/01_creating_disease_related_gene_lists_and_gene_sets/01_creating_ALS_gene_list.R
Rscript R/01_creating_disease_related_gene_lists_and_gene_sets/02_gene_enrichment_analysis.R
Rscript R/01_creating_disease_related_gene_lists_and_gene_sets/03_filter_out_non_significant_go_terms.R
Rscript R/01_creating_disease_related_gene_lists_and_gene_sets/04_filter_out_redundant_go_terms.R
Rscript R/01_creating_disease_related_gene_lists_and_gene_sets/05_converting _go_terms_to_gene_lists.R
Rscript R/01_creating_disease_related_gene_lists_and_gene_sets/06_analyse_dglinker_gene_lists.R
Rscript R/01_creating_disease_related_gene_lists_and_gene_sets/07_identify_disease_related_genes.R
Rscript R/01_creating_disease_related_gene_lists_and_gene_sets/08_convert_disease_related_gene_lists_to_entrez_ids.R
Rscript R/01_creating_disease_related_gene_lists_and_gene_sets/09_convert_non_disease_related_gene_lists_to_entrez_ids.R
Rscript R/01_creating_disease_related_gene_lists_and_gene_sets/10_convert_entrez_id_lists_to_magma_input_including_known_disease_genes.R
Rscript R/01_creating_disease_related_gene_lists_and_gene_sets/11_convert_entrez_id_lists_to_magma_input_excluding_known_disease_genes.R

sh shellScripts/02_magma/01_magma.sh
